### ISSUE TITLE
Concurrent access with geth

### ISSUE THREAD

**Issue by nasdf** [vulcanize/eth-statediff-service#58]
Is it possible to run the statediff service with an active geth node?  I know leveldb doesn't allow concurrent access but I'm interested in using this if you've found a work around.

**Comment by i-norden** [comment]
Hi @nasdf ! A work around is to use file system overlays, an example of that is in this startup script: https://github.com/vulcanize/eth-statediff-service/blob/master/startup_script.sh#L17

You can also run the geth embedded version of this service: https://github.com/vulcanize/go-ethereum/tree/statediff/statediff

The former is probably what you want to do if you want to parallelize the processing of historical data, the later is what you will need to run to track at head.

**Comment by i-norden** [comment]
And heads up, in order to sync the historical data within a reasonable amount of time it is necessary to horizontally scale out this stand-alone service many times over. At which point, the number of connections and load on the Postgres database becomes a bottleneck.

We're in the process of making updates to work around this. Including updating our primary and foreign keys to be natural keys (so that it is easier to shard and merge Postgres databases) and introducing a mode that allows you to write the SQL statements out to a file which can then be loaded using `psql < file.sql`.

https://github.com/vulcanize/ipld-eth-db/pull/18
https://github.com/vulcanize/go-ethereum/pull/152
https://github.com/vulcanize/eth-statediff-service/pull/54

**Comment by nasdf** [comment]
Awesome! I'll check out the filesystem overlay.  Good to know about the horizontal scaling.

My plan is to inject the diffs directly into the portal network so the database shouldn't be an issue here.

If I were to have a process subscribed to the latest diffs would it be able to keep up with the chain head?

Also can I use a non archive node to get diffs from the current head? I found this geth flag keeps the intermediate trie nodes around `--cache.preimages`.

**Comment by i-norden** [comment]
@nasdf yeah the embedded service can be ran in `--syncmode=full` without `--gcmode=archive` without any additional flag. And fyi `--cache.preimages` is terribly named/documented, and what it actually does it tells the geth node to retain leveldb bucket that maps address => keccak256(address) aka it stores "preimages" of the hashes used as the paths of leaf nodes in the state trie.

The embedded service can definitely keep up with head if in the mode where it writes directly to Postgres (`--statediff.writing`). It is dependent on having some rather beefy hardware, and you may need to increase the number of workers (`--statediff.workers`) or tweak your `--cache` allocations. More workers can provide more throughput but can also increase latency e.g. for your hardware it might take 30 seconds for a single worker to process a statediff which means it will fall behind, whereas with 20 workers it might take each one 2 minutes but in aggregate that provides a throughout of 10 statediffs per minute which is enough to keep up with head albeit with a ~2min lag behind it.

Note that if you run the statediffing service before your node has caught up with head, it will not be able to keep up with the batch processing used to sync a node up to head.

It's much harder to keep up with head when subscribing instead of writing directly. It's a lot of data to send over the wire and  when writing directly to Postgres we perform our data transformations and Postgres tx generation while we iterate the state a single time, whereas if we generate the statediff object and then send it over the wire we need to iterate state once to generate the object and then need to iterate the object again on the other end of the wire to process it into Postgres.
